# Generated by Django 4.1.2 on 2023-04-04 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
